rabbitmq:
  image: rabbitmq:3-management
  service:
    ports:
      - name: api
        port: 5672
      - name: management
        port: 15672

consumer:
  image: calawseliad/consumer:latest
  command: "python consumer.py -p 5672 -s rabbitmq"

producer:
  image: calawseliad/producer:latest
  command: "python producer.py -p 5672 -s rabbitmq -m 'Hello' -r 30"